title: "Edit tree-based lemmatizer"

vars:
  annotations: "assets/annotations.jsonl"
  tok2vec_config: "configs/edittree_tok2vec.cfg"
  trf_config: "configs/edittree_trf.cfg"
  train_file: "data/train.spacy"
  dev_file: "data/dev.spacy"
  test_file: "data/test.spacy"
  trained_model: "training/model-best"

directories: ["scripts", "configs", "assets", "data", "training"]

workflows:
  all:
    - train_cpu
    - train_gpu
    - train_trf_gpu

commands:
  - name: "train_cpu"
    help: "Train the lemmatization model on the CPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.tok2vec_config} --output training --paths.train ${vars.train_file} --paths.dev ${vars.dev_file}  -c ./scripts/custom_functions.py"
    deps:
      - ${vars.train_file}
      - ${vars.dev_file}
    outputs:
      - ${vars.trained_model}
  - name: "train_gpu"
    help: "Train the lemmatization model on the GPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.tok2vec_config} --output training --paths.train ${vars.train_file} --paths.dev ${vars.dev_file}  -c ./scripts/custom_functions.py --gpu-id 0"
    deps:
      - ${vars.train_file}
      - ${vars.dev_file}
    outputs:
      - ${vars.trained_model}
  - name: "train_trf_gpu"
    help: "Train the lemmatization model on the GPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.trf_config} --output training --paths.train ${vars.train_file} --paths.dev ${vars.dev_file}  -c ./scripts/custom_functions.py --gpu-id 0"
    deps:
      - ${vars.train_file}
      - ${vars.dev_file}
    outputs:
      - ${vars.trained_model}
