title: "Edit tree-based lemmatizer"

vars:
  lang: null
  config: null
  corpus: null
  gpu: -1

directories: ["scripts", "configs", "assets", "data", "training"]

assets:
    - dest: "assets/${vars.corpus}"
      git:
        repo: "git@github.com:explosion/spacy-data.git"
        branch: "master"
        path: "corpora/${vars.corpus}"

workflows:
  all:
    - preprocess
    - train

commands:
  - name: "preprocess"
    help: "Convert data to spaCy format"
    script:
      - "mkdir -p corpus/${vars.corpus}"
      - "python -m spacy convert -C assets/${vars.corpus}/train corpus/${vars.corpus}/"
      - "python -m spacy convert -C assets/${vars.corpus}/dev corpus/${vars.corpus}/"
      - "python -m spacy convert -C assets/${vars.corpus}/test corpus/${vars.corpus}/"
    deps:
      - "assets/${vars.corpus}/train"
      - "assets/${vars.corpus}/dev"
      - "assets/${vars.corpus}/test"
    outputs:
      - "corpus/${vars.corpus}/train.spacy"
      - "corpus/${vars.corpus}/dev.spacy"
      - "corpus/${vars.corpus}/test.spacy"

  - name: "train"
    help: "Train the lemmatization model evaluate on the dev corpus."
    script:
      - "python -m spacy train configs/${vars.config}.cfg --output training/${vars.config} --gpu-id ${vars.gpu} --paths.train corpus/${vars.corpus}/train.spacy --paths.dev corpus/${vars.corpus}/dev.spacy --nlp.lang=${vars.lang} -c ./scripts/custom_functions.py"
    deps:
      - "configs/${vars.config}.cfg"
      - "corpus/${vars.corpus}/train.spacy"
      - "corpus/${vars.corpus}/dev.spacy"
    outputs:
      - "training/${vars.corpus}/model-best"
